[package]
name = "scrobble"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
config.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
dioxus.workspace = true
