[application]
name = "rusic"
bundle_identifier = "com.temidaradev.rusic"

[application.assets]
# The folder which contains assets
base_path = "assets"

[web.app]
title = "rusic"

[web.resource]
# Additional CSS style files for web only
style = []
script = []

[web.resource.dev]
script = []

[web.tailwind]
input = "tailwind.css"
config = "tailwind.config.js"
