[application]
name = "rusic"
default_platform = "desktop"

[application.assets]
# The folder which contains assets
base_path = "rusic/assets"

[bundle]
identifier = "com.temidaradev.rusic"
publisher = "temidaradev"
icon = ["assets/logo.png"]

[web.app]
title = "rusic"

[web.resource]
# Additional CSS style files for web only
style = []
script = []

[web.resource.dev]
script = []

[web.tailwind]
input = "tailwind.css"
config = "tailwind.config.js"

