[package]
name = "server"
version = "0.3.1"
edition = "2024"

[dependencies]
jellyfin-sdk-rust = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
