[package]
name = "reader"
version = "0.3.1"
edition = "2024"

[dependencies]
lofty = { workspace = true }
serde = { workspace = true }
async-recursion = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
